apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "helm-source-ip-app.fullname" . }}
  labels:
    app: {{ template "helm-source-ip-app.name" . }}
    chart: {{ template "helm-source-ip-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  My__env: {{ .Values.configmap.param1 | quote }}
